import {writeFile} from 'node:fs/promises';
import path from 'node:path';
import {root} from './sources.mjs';
// Exact d20 enumeration, including natural 1/20 degree adjustments.
export function probabilities(attack,ac){
 let hit=0,critical=0;
 for(let die=1;die<=20;die++){
  const total=attack+die;
  let degree=total>=ac+10?3:total>=ac?2:total<=ac-10?0:1;
  if(die===20)degree=Math.min(3,degree+1);if(die===1)degree=Math.max(0,degree-1);
  if(degree===2)hit+=.05;if(degree===3)critical+=.05;
 }
 return {hit,critical,land:hit+critical,multiplier:hit+2*critical};
}
const rows=[];
for(const [level,baseAC] of [[1,15],[5,21],[7,24],[11,30],[15,36],[19,42]])for(const extraAC of [0,2]){
 const ac=baseAC+extraAC,str=level>=17?6:level>=10?5:4;
 const potency=level>=16?3:level>=10?2:level>=2?1:0;
 const dice=level>=19?4:level>=12?3:level>=4?2:1;
 const rank=level>=13?3:level>=5?2:1,fighterRank=level>=13?4:level>=5?3:2;
 const spec=level>=15?rank*2:level>=7?rank:0;
 const fighterSpec=level>=15?fighterRank*2:level>=7?fighterRank:0;
 const damage=dice*6.5+str+spec,fighterDamage=dice*6.5+str+fighterSpec;
 const attack=level+2*rank+str+potency,fighterAttack=level+2*fighterRank+str+potency;
 const first=probabilities(attack,ac),second=probabilities(attack-5,ac);
 const base=(first.multiplier+second.multiplier)*damage;
 const fighter=(probabilities(fighterAttack,ac).multiplier+probabilities(fighterAttack-5,ac).multiplier)*fighterDamage;
 const burstDice=1+Math.floor((level+1)/6);
 const sustained=base+(first.multiplier*dice+second.multiplier*burstDice*3.5)/2;
 let window;
 if(level<7)window=base+first.multiplier*burstDice*3.5;
 else {
  const increase=Math.floor((level-5)/6),follow=(2+increase)*3.5;
  window=[1,1,2].reduce((sum,n)=>sum+first.multiplier*(damage+(n+increase)*3.5)+first.land*follow+(1-first.land)*second.multiplier*damage,0)/3;
 }
 rows.push([level,ac,base,fighter,sustained,window]);
}
const text=`# Damage expectation worksheet\n\nGenerated by \`npm run balance\`. Values are expected damage per turn using two offensive actions and a two-handed d12 weapon. See PLAYTEST.md for assumptions and exclusions. Target ACs are explicit scenario inputs, not a complete creature model. Fundamental weapon runes enter at levels 2/4/10/12/16/19; an apex attribute increase is assumed at 17. No property runes, off-guard, feats, buffs, resistances, or protective reactions are included.\n\nThe normal martial baseline is two ordinary Strikes at normal MAP. Fighter has its higher proficiency and corresponding specialization, but no offensive feats. Sustainable Gunbreaker cycles Keen Edge → Brutal Shell → Solid Barrel → Burst Strike over two turns, with no cartridges spent on protection. The burst window is Burst Strike + Strike before level 7, then the three-turn Gnashing sequence with Continuation on a hit or a normal second Strike on a miss. These are illustrative routines, not optimized builds or a balance verdict.\n\n| Level | Target AC | Normal martial | Fighter | Gunbreaker basic cycle | Gunbreaker burst window |\n|---|---|---|---|---|---|\n${rows.map(row=>`| ${row.map((v,i)=>i<2?v:v.toFixed(2)).join(' | ')} |`).join('\n')}\n\nThe Gunbreaker burst column cannot be sustained: Gnashing Fang has a one-minute frequency and only one step can be used per turn. Lost reach or an intervening action removes the follow-up. Holding a cartridge for Heart of Stone reduces available offense. The basic cycle is deliberately a smaller improvement than the burst window. Compare full four-round encounters and ally damage prevention before tuning further.\n`;
if(process.argv[1] && path.resolve(process.argv[1])===path.join(root,'tools/balance.mjs')){
 await writeFile(path.join(root,'BALANCE.md'),text);console.log(text);
}
